[world]
name = "Overgoal"
seed = "overgoal1"

[namespace]
default = "overgoal"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"overgoal-OvergoalPlayer" = ["overgoal-overgoal_game", "overgoal-admin"]
"overgoal-Club" = ["overgoal-admin"]
"overgoal-Season" = ["overgoal-admin"]
"overgoal-SeasonClub" = ["overgoal-admin"]
"overgoal-SeasonPlayer" = ["overgoal-overgoal_game", "overgoal-admin"]

[init_call_args]
# Initialize overgoal-overgoal_game with the universe game contract address
"overgoal-overgoal_game" = ["0x6f30435136e0effaabd531196d4cdad746b712df6e1f35b1a2acdce5d6c1863"]
# Initialize overgoal-admin with the universe game contract address
"overgoal-admin" = ["0x6f30435136e0effaabd531196d4cdad746b712df6e1f35b1a2acdce5d6c1863"]